project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: "Luong Nguyen Thanh"
  description: "R code, environmental data science, and cats."
  site-url: https://jadeyryan.com
  repo-url: https://github.com/jadeynryan/jadey_website
  repo-actions:
    - source
    - issue
  twitter-card:
    creator: "@luongnt95"

  open-graph:
    locale: en_EN
  page-navigation: true
  cookie-consent:
    type: express
    prefs-text: "Change cookies üç™"

  navbar:
    pinned: true
    logo: assets/img/JR-logo-circle.webp
    left:
      - text: About
        icon: person-circle
        href: index.qmd
      - text: CV
        icon: file-earmark-text-fill
        href: cv.qmd
      # - text: Blog
      #   icon: pen-fill
      #   href: blog.qmd
      # - text: Talks
      #   icon: mic-fill
      #   href: talks.qmd
      # - text: Projects
      #   icon: puzzle-fill
      #   href: projects.qmd

    right:
      - icon: rss
        aria-label: rss
        href: blog.xml
      - icon: github
        aria-label: GitHub
        href: https://github.com/ntluong95
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/ntluong95/

  page-footer:
    border: true
    left: "&#169; 2024 Luong Nguyen Thanh"
    right: "Made with [Quarto Website](https://quarto.org)"

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Luong Nguyen Thanh | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y