project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!handbook/"
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: "Luong Nguyen Thanh"
  description: "R & Python code, global health and sustainability data science."
  site-url: https://ntluong95.github.io/profile
  repo-url: https://github.com/ntluong95/profile
  repo-actions:
    - source
    - issue
  twitter-card:
    creator: "@luongnt95"

  open-graph:
    locale: en_EN
  page-navigation: true
  cookie-consent:
    type: express
    prefs-text: "Change cookies üç™"

  navbar:
    pinned: true
    logo: assets/img/JR-logo-circle.webp
    left:
      - text: About me
        icon: person-circle
        href: index.qmd
      - text: Curriculum Vitae
        icon: file-earmark-text-fill
        href: cv.qmd
      - text: Personal Blog
        icon: pen-fill
        href: blog.qmd
      - text: Event organized
        icon: people-fill
        href: talks.qmd
      - text: Personal Projects
        icon: puzzle-fill
        href: projects.qmd

    right:
      - icon: rss
        aria-label: rss
        href: blog.xml
      - icon: github
        aria-label: GitHub
        href: https://github.com/ntluong95
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/ntluong95/

  page-footer:
    border: true
    left: "&#169; 2025 Luong Nguyen Thanh"
    right: "Made with [Quarto Website](https://quarto.org)"

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    css: styles.css
    toc: true
    toc-depth: 4
    pagetitle: "Luong Nguyen Thanh | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y


