project:
  type: book
  output-dir: ../docs/handbook

published-title: "Last updated"

babelquarto:
  languagecodes:
  - name: vn
    text: "Tiếng Việt"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['vn']    

title-vn: "Cẩm nang nghiên cứu sức khỏe: Hướng dẫn từ A-Z để thành công trong sự nghiệp"
lang: en

book:
  title: "The Health Researcher's Roadmap: An A-Z Handbook for Career Success"
  author: "Luong Nguyen Thanh"
  date: "2025-09-19"
  repo-url: https://github.com/ntluong95/profile/tree/main/handbook
  site-url: https://example.com
  open-graph: true
  repo-actions: [edit, issue, source]
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd # draft
    - introduction.qmd # draft
    - part: "Public Health: Theory and Application"
      part-vn: "Y tế công cộng: Lý thuyết và Ứng dụng"
      chapters:
        - pages/epi_basic.qmd # draft
        - pages/big_concept.qmd # draft
        - pages/study_design.qmd # draft
    - part: "Biostatistics: Methods and Practice"
      part-vn: "Sinh học thống kê: Phương pháp và Thực hành"
      chapters:
        - pages/biostats_basic.qmd # draft
        - pages/regression.qmd # draft
        - pages/survival.qmd # draft
        - pages/longitudinal.qmd # draft
        - pages/machine_learning.qmd # draft
        - pages/mathematical_modelling.qmd # draft
        - pages/meta_analysis.qmd # draft

    - part: "Data Science: Tools and Techniques"
      part-vn: "Khoa học dữ liệu: Công cụ và Kỹ thuật"
      chapters:
        - pages/programming.qmd # draft
        - pages/free_database.qmd # draft
        - pages/data_management.qmd # draft
        - pages/statistical_software.qmd # draft
        - pages/data_visualization.qmd # draft
        - pages/dashboard.qmd # draft
        - pages/cloud_database.qmd # draft

    - pages/summary.qmd # draft
    - pages/references.qmd # draft

bibliography: references.bib

format:
  html:
    theme: [cosmo.scss, theme.scss]
    include-after-body: [posthog.html, misc.html]


editor:
  markdown:
    wrap: sentence
    canonical: true
